[package]
name = "rreplace"
version = "0.1.0"
authors = ["Leonard Ehrenfried <leonard.ehrenfried@gmail.com>"]

[dependencies]
gitignore = "1.0.5"
glob = "0.2.11"

[dependencies.clap]
version = "2.19.3"
default-features = false
